### ISSUE TITLE
flowcell API query returns samples from all projects associated with that flow cell, not just samples on that flow cell

### ISSUE THREAD

**Issue by dkoppstein** [maxplanck-ie/parkour2#29]
For example, 

```
res = requests.get(url, auth=(user,pw), verify=cert, params={'flowcell_id':'HKHYCDRX2'})
plis = []
for s in res.json(['2517_Förtsch_Akhtar']):
    plis.append(res.json()['2517_Förtsch_Akhtar'][s][1])
set(plis)
```

yields
```
{'CUTandTag-seq', 'CUTandRUN-seq'}
```
even though only CUTandRUN-seq samples are present in that flowcell, but CUTandTAG-seq samples are present in the project on different flowcells.

**Comment by adRn-s** [comment]
This project is not the first one that is spread across >1 flowcell. I wonder how we managed this in the past. Anyway, please share the value of `url` variable, I'm having difficulties following which API endpoint you're hitting.

**Comment by dkoppstein** [comment]
https://parkour.ie-freiburg.mpg.de/api/analysis_list/analysis_list/

**Comment by adRn-s** [comment]
Ok, I will have to check `FlowcellAnalysisViewSet.analysis_list()` @ `flowcell/views.py`... currently it's returning a dictionary with projects as keys... 🤔
