### ISSUE TITLE
Usage counts not consistent

### ISSUE THREAD

**Issue by nicolazilio** [maxplanck-ie/parkour2#44]
Hello,

In my quest to adapt Parkour to the needs of our institute I've realized that sometimes the sum of the counts for "Libraries and Samples" under "Usage" doesn't match that for the other three graphs. The reason is that `RecordsUsage` pulls libraries and samples using their own `create_time`, while the other API views (`OrganizationsUsage`, etc.) do so using the request's `create_time`.

I think it makes more sense to use the request's `create_time`, meaning that `RecordsUsage` can be easily amended to the following to match the other views

```python
class RecordsUsage(APIView):
    permission_classes = (IsAdminUser,)

    def get(self, request):
        start, end = get_date_range(request, "%Y-%m-%dT%H:%M:%S")

        libraries = Library.objects.filter(
            request__isnull=False,
            request__create_time__gte=start,
            request__create_time__lte=end,
        ).only("id")

        samples = Sample.objects.filter(
            request__isnull=False,
            request__create_time__gte=start,
            request__create_time__lte=end,
        ).only("id")

        return Response(
            [
                {
                    "name": "Libraries",
                    "data": len(libraries),
                },
                {
                    "name": "Samples",
                    "data": len(samples),
                },
            ]
        )
```
Yet, this raises the question as to which records should be shown here. At the moment all libraries/samples, whether from completed requests or not, with any status are shown, as long as they were created within the supplied date range. Does this make sense? Or would it be better to show, for example, only those from requests that have been at least submitted? What do you think?

**Comment by adRn-s** [comment]
I think this (together with `<url>/report`) is only used for yearly reports that the heads of both sequencing and bioinformatics facility submit. So, it wouldn't harm if we were to show only requests that were actually submitted.

In any case, these plots probably would be better off using the same criteria as `<url>/report`. Unless I'm mistaken, everywhere possible, we'd be using flowcell's create time.
